framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~ # ty była ~ / session.handler.native_file
    #    save_path: '%kernel.root_dir%/sessions'     # a tego nie było

    #esi: true
    #fragments: true
    php_errors:
        log: true

    assets: ~

parameters:
    photos_directory: '%kernel.project_dir%/public/uploads/photos'